// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Restaurant_API.Models
{
    public partial class RestaurantDBContext : DbContext
    {
        public RestaurantDBContext()
        {
        }

        public RestaurantDBContext(DbContextOptions<RestaurantDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<MenuItem> MenuItems { get; set; }
        public virtual DbSet<MenuItemSize> MenuItemSizes { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderItem> OrderItems { get; set; }
        public virtual DbSet<Size> Sizes { get; set; }

//        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
//        {
//            if (!optionsBuilder.IsConfigured)
//            {
//#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
//                optionsBuilder.UseSqlServer("Data Source=DESKTOP-NP9ERV5\\SQLEXPRESS;Initial Catalog=RestaurantDB;Integrated Security=True");
//            }
//        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<MenuItemSize>(entity =>
            {
                entity.HasKey(e => new { e.MenuItemId, e.SizeId })
                    .HasName("PK__MenuItem__317827B5B9A9EEA0");

                entity.HasOne(d => d.MenuItem)
                    .WithMany(p => p.MenuItemSizes)
                    .HasForeignKey(d => d.MenuItemId)
                    .HasConstraintName("FK__MenuItemS__MenuI__3A81B327");

                entity.HasOne(d => d.Size)
                    .WithMany(p => p.MenuItemSizes)
                    .HasForeignKey(d => d.SizeId)
                    .HasConstraintName("FK__MenuItemS__SizeI__3B75D760");
            });

            modelBuilder.Entity<OrderItem>(entity =>
            {
                entity.HasKey(e => new { e.OrderId, e.MenuItemId, e.SizeId })
                    .HasName("PK__OrderIte__8087D9B4ACDED213");

                entity.HasOne(d => d.MenuItem)
                    .WithMany(p => p.OrderItems)
                    .HasForeignKey(d => d.MenuItemId)
                    .HasConstraintName("FK__OrderItem__MenuI__412EB0B6");

                entity.HasOne(d => d.Order)
                    .WithMany(p => p.OrderItems)
                    .HasForeignKey(d => d.OrderId)
                    .HasConstraintName("FK__OrderItem__Order__403A8C7D");

                entity.HasOne(d => d.Size)
                    .WithMany(p => p.OrderItems)
                    .HasForeignKey(d => d.SizeId)
                    .HasConstraintName("FK__OrderItem__SizeI__4222D4EF");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}